"""nomeando coluna

Revision ID: d24a78a620a5
Revises: 19f7b8a4f4e2
Create Date: 2026-03-24 19:23:31.115239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd24a78a620a5'
down_revision = '19f7b8a4f4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_hash', sa.String(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('token_hash'))
        batch_op.create_unique_constraint(None, ['refresh_token_hash'])
        batch_op.drop_column('token_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('token_hash'), ['token_hash'], unique=True)
        batch_op.drop_column('refresh_token_hash')

    # ### end Alembic commands ###
