"""tabela de auth

Revision ID: d60fe51bd58f
Revises: 
Create Date: 2026-03-19 10:21:43.292680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60fe51bd58f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_auth_email')
    )
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_uuid'))
        batch_op.drop_index(batch_op.f('ix_auth_email'))

    op.drop_table('auth')
    # ### end Alembic commands ###
